
excluded:
  - Pods
  - IssueTracker15Tests
  - RegularExpressionCheckerUnitTest
  - IssueTracker15/SupportingFiles/AppDelegate.swift
  - IssueTracker15/SupportingFiles/SceneDelegate.swift
  
disabled_rules:
  - trailing_whitespace
  - identifier_name
  - line_length


